version: 2

sources:
  - name: raw
    database: flash-audio-486218-h6
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product

      - name: sales
        identifier: raw_gz_sales

      - name: ship
        identifier: raw_gz_ship

